feat(ci): Tagging workflow for policy in a directory
Updates the reusable workflow used to tag policy allowing users to use it for policies living in a subdirectory. This is useful for repositories with multiple policies

Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>

diff --git a/.github/workflows/reusable-release-tag.yml b/.github/workflows/reusable-release-tag.yml
--- a/.github/workflows/reusable-release-tag.yml
+++ b/.github/workflows/reusable-release-tag.yml
@@ -9,6 +9,15 @@ on:
         description: "Tag and trigger release manually"
         required: false
         default: true
+      policy-working-dir:
+        description: "working directory under policies folder"
+        required: false
+        type: string
+        default: ""
+      continue-on-error:
+        required: false
+        default: false
+        type: boolean
 
 jobs:
   tag-and-release:
@@ -18,6 +27,7 @@ jobs:
       github.event.inputs.trigger_release == 'true'
     name: Tag and push, triggering release
     runs-on: ubuntu-latest
+    continue-on-error: ${{ inputs.continue-on-error }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
@@ -26,25 +36,40 @@ jobs:
 
       - name: Extract version from metadata.yml
         id: extract-version
+        shell: bash
         run: |
-          if [ -f metadata.yml ]; then
-            VERSION=$(yq e '.annotations."io.kubewarden.policy.version"' metadata.yml)
-            if [ -z "$VERSION" ]; then
-              echo "annotation 'io.kubewarden.policy.version' is missing in metadata.yml"
-              exit 1
+          POLICY_DIR="${{ inputs.policy-working-dir }}"
+          POLICY_NAME=""
+          FILES=("metadata.yml" "metadata.yaml")
+          VERSION=""
+          for F in "${FILES[@]}"; do
+            FILE="$F"
+            if [ -n "$POLICY_DIR" ]; then
+              if [ -f "$POLICY_DIR" ]; then
+                echo "The policy directory does not exists: $POLICY_DIR"
+                exit 1
+              fi
+              FILE="$POLICY_DIR/$F"
+              # policy dir can have multiple directories. Assume the last one
+              # to be the policy-name
+              POLICY_NAME="$(basename $POLICY_DIR)"
             fi
-          elif [ -f metadata.yaml ]; then
-            VERSION=$(yq e '.annotations."io.kubewarden.policy.version"' metadata.yaml)
-            if [ -z "$VERSION" ]; then
-              echo "annotation 'io.kubewarden.policy.version' is missing in metadata.yaml"
-              exit 1
+            if [ -f "$FILE" ]; then
+              VERSION="v$(yq e '.annotations."io.kubewarden.policy.version"' $FILE)"
+              if [ -z "$VERSION" ]; then
+                echo "annotation 'io.kubewarden.policy.version' is missing in $FILE"
+                exit 1
+              fi
+              if  [ -n "$POLICY_NAME" ]; then
+                VERSION="$POLICY_NAME/$VERSION"
+              fi
+              echo "found version $VERSION"
+              echo "VERSION=$VERSION" >> $GITHUB_ENV
+              exit 0
             fi
-          else
-            echo "Error: metadata.yml or metadata.yaml not found" >&2
-            exit 1
-          fi
-          echo "found version $VERSION"
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          done
+          echo "Error: metadata.yml or metadata.yaml not found" >&2
+          exit 1
 
       - name: Configure Git author
         run: |
@@ -55,11 +80,11 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git tag -a "v$VERSION" -m "Release version $VERSION"
-          git push origin "v$VERSION"
+          git tag -a "$VERSION" -m "Release version $VERSION"
+          git push origin "$VERSION"
 
       - name: Trigger release workflow
-        run: gh workflow run release.yml --ref "v$VERSION"
+        run: gh workflow run release.yml --ref "$VERSION"
         env:
           GH_TOKEN: ${{ github.token }}
 
